namespace LocalizationLibrary
{
    public interface IStrings
    {
        string WindowTitle { get; }
        string TabDefault { get; }
        string TabTwoWay { get; }
        string TabOneTime { get; }
        string TabOneWay { get; }
        string TabTriggers { get; }
        string LanguageSelector { get; }
        string LanguageEnglish { get; }
        string LanguageRussian { get; }
        string DefaultBindingTitle { get; }
        string DefaultBindingDescription { get; }
        string ElementBinding { get; }
        string EnterText { get; }
        string Result { get; }
        string Slider { get; }
        string Value { get; }
        string ViewModelBinding { get; }
        string CheckBox { get; }
        string State { get; }
        string SliderVM { get; }
        string ComboBox { get; }
        string SelectedIndex { get; }
        string TwoWayTitle { get; }
        string TwoWayDescription { get; }
        string ElementBindingTwoWay { get; }
        string TextBox1 { get; }
        string TextBox2 { get; }
        string SyncText { get; }
        string ViewModelBindingTwoWay { get; }
        string Display { get; }
        string Progress { get; }
        string Enable { get; }
        string OptionA { get; }
        string OptionB { get; }
        string OptionC { get; }
        string ResetAll { get; }
        string OneTimeTitle { get; }
        string OneTimeDescription { get; }
        string CompareOneTime { get; }
        string ForComparison { get; }
        string ValueInVM { get; }
        string UpdateVMValues { get; }
        string OneTimeNotUpdated { get; }
        string SliderComparison { get; }
        string UpdateVMValues2 { get; }
        string OneTimeNotChanged { get; }
        string CurrentTimeOneTime { get; }
        string FixedOneTime { get; }
        string ActualOneWay { get; }
        string UpdateTimeVM { get; }
        string OneTimeDesc { get; }
        string OneWayTitle { get; }
        string OneWayDescription { get; }
        string OneWayFromVM { get; }
        string OneWayDesc1 { get; }
        string TextOneWay { get; }
        string TextBoxOneWay { get; }
        string ProgressOneWay { get; }
        string UpdateSourceData { get; }
        string OneWayDesc2 { get; }
        string OneWayToSource { get; }
        string OneWayToSourceDesc { get; }
        string EnterText2 { get; }
        string ReceivedInVM { get; }
        string OneWayToSourceDesc2 { get; }
        string SliderOneWayToSource { get; }
        string ChangeSliderInVM { get; }
        string OneWayToSourceDesc3 { get; }
        string TriggersTitle { get; }
        string TriggersDescription { get; }
        string Trigger1 { get; }
        string Trigger1Desc { get; }
        string EnableButton { get; }
        string TriggerButtonText { get; }
        string Trigger2 { get; }
        string Trigger2Desc { get; }
        string Ok { get; }
        string Error { get; }
        string Reset { get; }
        string Trigger3 { get; }
        string Trigger3Desc { get; }
        string ConditionA { get; }
        string ConditionB { get; }
        string SelectBothConditions { get; }
        string BothConditionsMet { get; }
        string Trigger4 { get; }
        string Trigger4Desc { get; }
        string HoverMe { get; }
        string LoadedAnimation { get; }
        string StatusNone { get; }
        string StatusOk { get; }
        string StatusError { get; }
        string Item1 { get; }
        string Item2 { get; }
        string Item3 { get; }
    }
}
